---
- Network:
    - AdGuard Home:
        href: http://adguard.local/
        icon: adguard-home.png
        description: Network-wide Ad Blocking

    - AdGuard Home Sync:
        href: http://adguard-sync.local/
        icon: adguard-home.png

- Infrastructure:
    - Proxmox:
        icon: proxmox.png
        href: http://pve.local/
        description: Proxmox Virtual Environment

    - Proxmox Backup Server:
        icon: proxmox.png
        href: http://pbs.local/
        description: Proxmox Backup Server
        
    - NAS:
        icon: synology.png
        href: http://nas.local/
        description: Synology NAS