## --- RECONCILE STATE ---
- name: "Determine if should app is assigned to this host: {{ apps_app_name }}"
  ansible.builtin.set_fact:
    apps_is_assigned: "{{ apps_app_name in (app_mapping.get(inventory_hostname) | default([])) }}"

## --- NETWORKING (DNS FIX) ---
- name: Fix port 53 conflict for adguard
  when:
    - apps_app_name == "adguard"
    - apps_is_assigned | bool
  block:
    - name: Disable systemd-resolved DNSStubListener
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNSStubListener='
        line: 'DNSStubListener=no'
        owner: root
        group: root
        mode: '0644'
      notify: Restart systemd-resolved

    - name: Force symlink for resolv.conf
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true

    - name: Flush handlers to clear port 53
      ansible.builtin.meta: flush_handlers

## --- FILE MANAGEMENT ---
- name: "Ensure directory exists for {{ apps_app_name }}"
  ansible.builtin.file:
    path: "{{ apps_base_dir }}/{{ apps_app_name }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: apps_is_assigned | bool

- name: "Sync compose file for {{ apps_app_name }}"
  ansible.builtin.template:
    owner: root
    group: root
    mode: '0600'
    src: "{{ playbook_dir }}/../apps/{{ apps_app_name }}/docker-compose.yml.j2"
    dest: "{{ apps_base_dir }}/{{ apps_app_name }}/docker-compose.yml"
  when: apps_is_assigned | bool

- name: "Configure app-specific files"
  when:
    - apps_is_assigned | bool
    - apps_app_name in apps_config_map
  block:
    - name: "Ensure config directory exists for {{ apps_app_name }} "
      ansible.builtin.file:
        path: "{{ apps_config_map[apps_app_name].config_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "Sync configuration files for {{ apps_app_name }}"
      ansible.builtin.copy:
        src: "{{ apps_config_map[apps_app_name].src_dir }}/{{ item }}"
        dest: "{{ apps_config_map[apps_app_name].config_dir }}/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ apps_config_map[apps_app_name].files }}"

## --- DOCKER ENFORCEMENT ---
- name: "Check app project directory for {{ apps_app_name }}"
  ansible.builtin.stat:
    path: "{{ apps_base_dir }}/{{ apps_app_name }}"
  register: apps_app_project_dir

- name: "Set Docker Compose state for {{ apps_app_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ apps_base_dir }}/{{ apps_app_name }}"
    state: "{{ 'present' if apps_is_assigned else 'absent' }}"
    wait: true
  when:
    - apps_is_assigned | bool
    - apps_app_project_dir.stat.exists | default(false)

- name: "Final cleanup for {{ apps_app_name }}"
  ansible.builtin.file:
    path: "{{ apps_base_dir }}/{{ apps_app_name }}"
    state: absent
  when: not apps_is_assigned | bool
