- name: Deploy or remove managed applications
  ansible.builtin.include_tasks: deploy_app.yml
  loop: "{{ apps_managed_apps }}"
  loop_control:
    loop_var: apps_app_name
  tags: apps

- name: Prune unused Docker objects
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: false
  tags: apps
