services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "8888:80"     # HTTP
      - "4443:443"   # HTTPS
      - "8080:8080" # Dashboard (Optional: remove if using labels for access)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./traefik.yml:/etc/traefik/traefik.yml:ro # Uncomment if using a config file
    command:
      # Enable Dashboard
      - --api.insecure=true 
      - --api.dashboard=true
      # Docker Provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    networks:
      - web

networks:
  web:
    external: false