name: adguardhome

services:
  adguardhome:
    image: adguard/adguardhome
    restart: always
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 80:80/tcp # http web interface
      - 3000:3000/tcp # initial setup web interface
    volumes:
      - /mnt/docker_data/adguard/config:/opt/adguardhome/conf # app configuration
      - /mnt/docker_data/adguard/work:/opt/adguardhome/work # app working directory
    labels:
      - "homepage.group=Network"
      - "homepage.name=AdGuard Home"
      - "homepage.icon=adguard-home.png"
      - "homepage.href=http://10.1.10.200:80/" # Your AdGuard IP
      - "homepage.description=Network-wide Ad Blocking"

      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.local`)"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.rule=Host(`10.1.10.200:3000`)"
      - "traefik.http.routers.adguard.entrypoints=web"

volumes:
  config:
    driver: local
  work:
    driver: local
