- name: Install dependencies
  ansible.builtin.apt:
    name: [curl, git, gnupg, ca-certificates]
    state: present
    update_cache: true
  tags: docker

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: docker

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags: docker

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repository_url }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  tags: docker

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  tags: docker
