[vms]
test-docker-01 ansible_host=10.1.10.200
prod-docker-01 ansible_host=10.1.10.100

[rpis]
# ubuntu-rpi3-0 ansible_host=10.1.10.90 BORKED?
ubuntu-rpi3-1 ansible_host=10.1.10.91
ubuntu-rpi3-2 ansible_host=10.1.10.92
ubuntu-rpi4-0 ansible_host=10.1.10.93
ubuntu-rpi4-1 ansible_host=10.1.10.94