- name: Configure VM hosts
  hosts: vms
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - storage
    - docker
    - apps

- name: Configure Raspberry Pi hosts
  hosts: rpis
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - docker
    - apps
